export const companies = [
  {
    name: "ABC Corporation",
    selected: false,
    id: 1,
    address: "123 Main Street, Anytown",
  },
  {
    name: "XYZ Industries",
    selected: false,
    id: 2,
    address: "456 Elm Street, Anycity",
  },
  {
    name: "Smith & Sons",
    selected: false,
    id: 3,
    address: "789 Oak Avenue, Anyvillage",
  },
  {
    name: "Johnson Enterprises",
    selected: false,
    id: 4,
    address: "567 Pine Street, Anytown",
  },
  {
    name: "Miller Co.",
    selected: false,
    id: 5,
    address: "901 Maple Avenue, Anycity",
  },
  {
    name: "Wilson & Associates",
    selected: false,
    id: 6,
    address: "345 Cedar Street, Anyvillage",
  },
  {
    name: "Brown Corporation",
    selected: false,
    id: 7,
    address: "234 Birch Avenue, Anytown",
  },
  {
    name: "Green Industries",
    selected: false,
    id: 8,
    address: "678 Oak Street, Anycity",
  },
  {
    name: "Davis & Co.",
    selected: false,
    id: 9,
    address: "890 Pine Avenue, Anyvillage",
  },
  {
    name: "Clark Enterprises",
    selected: false,
    id: 10,
    address: "456 Maple Street, Anytown",
  },
  {
    name: "Anderson Corp.",
    selected: false,
    id: 11,
    address: "789 Elm Avenue, Anycity",
  },
  {
    name: "White Company",
    selected: false,
    id: 12,
    address: "123 Cedar Street, Anyvillage",
  },
  {
    name: "Thomas Inc.",
    selected: false,
    id: 13,
    address: "456 Birch Street, Anytown",
  },
  {
    name: "Lee & Sons",
    selected: false,
    id: 14,
    address: "789 Oak Avenue, Anycity",
  },
  {
    name: "Gonzalez Corporation",
    selected: false,
    id: 15,
    address: "123 Pine Street, Anyvillage",
  },
  {
    name: "Harris Industries",
    selected: false,
    id: 16,
    address: "456 Maple Avenue, Anytown",
  },
  {
    name: "Martin Co.",
    selected: false,
    id: 17,
    address: "789 Elm Street, Anycity",
  },
  {
    name: "Scott & Associates",
    selected: false,
    id: 18,
    address: "123 Cedar Avenue, Anyvillage",
  },
  {
    name: "Young Enterprises",
    selected: false,
    id: 19,
    address: "456 Birch Street, Anytown",
  },
  {
    name: "King Corporation",
    selected: false,
    id: 20,
    address: "789 Oak Street, Anycity",
  },
];
