export const employees = [
  {
    firstName: "John",
    secondName: "Doe",
    jobTitle: "Software Engineer",
    selected: false,
    id: 1,
    companyId: 5,
  },
  {
    firstName: "Jane",
    secondName: "Doe",
    jobTitle: "Data Analyst",
    selected: false,
    id: 2,
    companyId: 8,
  },
  {
    firstName: "Alex",
    secondName: "Smith",
    jobTitle: "UI/UX Designer",
    selected: false,
    id: 3,
    companyId: 8,
  },
  {
    firstName: "Emily",
    secondName: "Johnson",
    jobTitle: "Project Manager",
    selected: false,
    id: 4,
    companyId: 12,
  },
  {
    firstName: "Michael",
    secondName: "Brown",
    jobTitle: "Marketing Specialist",
    selected: false,
    id: 5,
    companyId: 2,
  },
  {
    firstName: "Jessica",
    secondName: "Wilson",
    jobTitle: "Financial Analyst",
    selected: false,
    id: 6,
    companyId: 13,
  },
  {
    firstName: "William",
    secondName: "Taylor",
    jobTitle: "Software Developer",
    selected: false,
    id: 7,
    companyId: 11,
  },
  {
    firstName: "Olivia",
    secondName: "Martinez",
    jobTitle: "Product Manager",
    selected: false,
    id: 8,
    companyId: 1,
  },
  {
    firstName: "James",
    secondName: "Anderson",
    jobTitle: "Systems Engineer",
    selected: false,
    id: 9,
    companyId: 8,
  },
  {
    firstName: "Sophia",
    secondName: "Thomas",
    jobTitle: "Graphic Designer",
    selected: false,
    id: 10,
    companyId: 2,
  },
  {
    firstName: "Daniel",
    secondName: "Hernandez",
    jobTitle: "Business Analyst",
    selected: false,
    id: 11,
    companyId: 14,
  },
  {
    firstName: "Isabella",
    secondName: "Young",
    jobTitle: "Software Engineer",
    selected: false,
    id: 12,
    companyId: 18,
  },
  {
    firstName: "Liam",
    secondName: "King",
    jobTitle: "Web Developer",
    selected: false,
    id: 13,
    companyId: 16,
  },
  {
    firstName: "Mia",
    secondName: "Garcia",
    jobTitle: "UX Designer",
    selected: false,
    id: 14,
    companyId: 10,
  },
  {
    firstName: "Benjamin",
    secondName: "Lopez",
    jobTitle: "Data Scientist",
    selected: false,
    id: 15,
    companyId: 11,
  },
  {
    firstName: "Charlotte",
    secondName: "Brown",
    jobTitle: "Marketing Manager",
    selected: false,
    id: 16,
    companyId: 13,
  },
  {
    firstName: "Ethan",
    secondName: "Lee",
    jobTitle: "Frontend Developer",
    selected: false,
    id: 17,
    companyId: 20,
  },
  {
    firstName: "Amelia",
    secondName: "Clark",
    jobTitle: "Software Engineer",
    selected: false,
    id: 18,
    companyId: 15,
  },
  {
    firstName: "Alexander",
    secondName: "Lewis",
    jobTitle: "UX/UI Designer",
    selected: false,
    id: 19,
    companyId: 7,
  },
  {
    firstName: "Harper",
    secondName: "Walker",
    jobTitle: "Project Coordinator",
    selected: false,
    id: 20,
    companyId: 9,
  },
  {
    firstName: "Jacob",
    secondName: "Wright",
    jobTitle: "Software Developer",
    selected: false,
    id: 21,
    companyId: 3,
  },
  {
    firstName: "Ava",
    secondName: "Hall",
    jobTitle: "Product Designer",
    selected: false,
    id: 22,
    companyId: 6,
  },
  {
    firstName: "Logan",
    secondName: "Green",
    jobTitle: "IT Specialist",
    selected: false,
    id: 23,
    companyId: 2,
  },
  {
    firstName: "Ella",
    secondName: "Adams",
    jobTitle: "Software Engineer",
    selected: false,
    id: 24,
    companyId: 3,
  },
  {
    firstName: "Lucas",
    secondName: "Evans",
    jobTitle: "Systems Analyst",
    selected: false,
    id: 25,
    companyId: 4,
  },
  {
    firstName: "Grace",
    secondName: "Parker",
    jobTitle: "UI Developer",
    selected: false,
    id: 26,
    companyId: 7,
  },
  {
    firstName: "Aiden",
    secondName: "Morris",
    jobTitle: "Digital Marketing Specialist",
    selected: false,
    id: 27,
    companyId: 6,
  },
  {
    firstName: "Luna",
    secondName: "Phillips",
    jobTitle: "Content Writer",
    selected: false,
    id: 28,
    companyId: 14,
  },
  {
    firstName: "Matthew",
    secondName: "Rivera",
    jobTitle: "Software Engineer",
    selected: false,
    id: 29,
    companyId: 18,
  },
  {
    firstName: "Chloe",
    secondName: "Cook",
    jobTitle: "UX Researcher",
    selected: false,
    id: 30,
    companyId: 3,
  },
  {
    firstName: "Jackson",
    secondName: "Bennett",
    jobTitle: "Software Developer",
    selected: false,
    id: 31,
    companyId: 19,
  },
  {
    firstName: "Penelope",
    secondName: "Ward",
    jobTitle: "Technical Writer",
    selected: false,
    id: 32,
    companyId: 16,
  },
  {
    firstName: "Ryan",
    secondName: "Russell",
    jobTitle: "Database Administrator",
    selected: false,
    id: 33,
    companyId: 6,
  },
  {
    firstName: "Zoey",
    secondName: "Hill",
    jobTitle: "Web Designer",
    selected: false,
    id: 34,
    companyId: 6,
  },
  {
    firstName: "Nathan",
    secondName: "Sanders",
    jobTitle: "Software Engineer",
    selected: false,
    id: 35,
    companyId: 15,
  },
  {
    firstName: "Madison",
    secondName: "Price",
    jobTitle: "Business Development Manager",
    selected: false,
    id: 36,
    companyId: 12,
  },
  {
    firstName: "Henry",
    secondName: "Barnes",
    jobTitle: "Systems Architect",
    selected: false,
    id: 37,
    companyId: 15,
  },
  {
    firstName: "Sofia",
    secondName: "Cole",
    jobTitle: "UI/UX Designer",
    selected: false,
    id: 38,
    companyId: 17,
  },
  {
    firstName: "Samuel",
    secondName: "Gonzalez",
    jobTitle: "Software Engineer",
    selected: false,
    id: 39,
    companyId: 2,
  },
  {
    firstName: "Evelyn",
    secondName: "Mitchell",
    jobTitle: "Frontend Developer",
    selected: false,
    id: 40,
    companyId: 7,
  },
];
